// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1jJ_vXVubf9XVxpuaVox9j7gyXAb0aYU',
    appId: '1:16500192762:web:de4ff836427494231f6043',
    messagingSenderId: '16500192762',
    projectId: 'survey-app-f029a',
    authDomain: 'survey-app-f029a.firebaseapp.com',
    storageBucket: 'survey-app-f029a.firebasestorage.app',
    measurementId: 'G-PZLYGMBNTT',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1jJ_vXVubf9XVxpuaVox9j7gyXAb0aYU',
    appId: '1:16500192762:web:cea7977f2b0dcfc41f6043',
    messagingSenderId: '16500192762',
    projectId: 'survey-app-f029a',
    authDomain: 'survey-app-f029a.firebaseapp.com',
    storageBucket: 'survey-app-f029a.firebasestorage.app',
    measurementId: 'G-6RCF1TBHVQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCbXurXbSTuw-M36NAh_oQzDMkzQziAeE',
    appId: '1:16500192762:ios:69e299f0d6ea929e1f6043',
    messagingSenderId: '16500192762',
    projectId: 'survey-app-f029a',
    storageBucket: 'survey-app-f029a.firebasestorage.app',
    iosClientId: '16500192762-3lm7bvdtuh7hddsghq51b83c722pjhed.apps.googleusercontent.com',
    iosBundleId: 'com.example.surveyadmin',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCbXurXbSTuw-M36NAh_oQzDMkzQziAeE',
    appId: '1:16500192762:ios:69e299f0d6ea929e1f6043',
    messagingSenderId: '16500192762',
    projectId: 'survey-app-f029a',
    storageBucket: 'survey-app-f029a.firebasestorage.app',
    iosClientId: '16500192762-3lm7bvdtuh7hddsghq51b83c722pjhed.apps.googleusercontent.com',
    iosBundleId: 'com.example.surveyadmin',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCheY1dcPOaftr1ea7yOpWJBRpLfMjJVds',
    appId: '1:16500192762:android:628bbbb539827ec31f6043',
    messagingSenderId: '16500192762',
    projectId: 'survey-app-f029a',
    storageBucket: 'survey-app-f029a.firebasestorage.app',
  );

}