// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1jJ_vXVubf9XVxpuaVox9j7gyXAb0aYU',
    appId: '1:16500192762:web:00632d083a23cbdb1f6043',
    messagingSenderId: '16500192762',
    projectId: 'survey-app-f029a',
    authDomain: 'survey-app-f029a.firebaseapp.com',
    storageBucket: 'survey-app-f029a.firebasestorage.app',
    measurementId: 'G-7F02NQTB5R',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1jJ_vXVubf9XVxpuaVox9j7gyXAb0aYU',
    appId: '1:16500192762:web:00632d083a23cbdb1f6043',
    messagingSenderId: '16500192762',
    projectId: 'survey-app-f029a',
    authDomain: 'survey-app-f029a.firebaseapp.com',
    storageBucket: 'survey-app-f029a.firebasestorage.app',
    measurementId: 'G-7F02NQTB5R',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCbXurXbSTuw-M36NAh_oQzDMkzQziAeE',
    appId: '1:16500192762:ios:21128b1cbdb9eec61f6043',
    messagingSenderId: '16500192762',
    projectId: 'survey-app-f029a',
    storageBucket: 'survey-app-f029a.firebasestorage.app',
    iosBundleId: 'com.example.surveyadmin',
  );

}